### ISSUE TITLE
Catalina - unsigned code

### ISSUE THREAD

**Issue by Vfisa** [tuxu/ipynb-quicklook#6]
Developer cannot be verified.
<img width="459" alt="Screen Shot 2019-10-30 at 10 51 39" src="https://user-images.githubusercontent.com/2714554/67884631-66d1a600-fb03-11e9-8221-2f9285f56297.png">

**Comment by samuelduchesne** [comment]
In the meantime, this can be fixed by removing the QuickLook preview generator from the quarantine.

Open up the terminal and type:

```
xattr -d com.apple.quarantine /Library/QuickLook/ipynb-quicklook.qlgenerator
qlmanage -r
killall Finder
```

1. This first command removes the preview generator from the quarantine permanently. Btw, you can do the same for other apps if needed.
2. The second command restarts the Quick Look Server debug and management tool.
3. The third command restarts the Finder. I found that was necessary after restarting the Quick Look manager.

**Comment by istar0me** [comment]
@samuelduchesne Thanks! It works like a charm :)

**Comment by tuxu** [comment]
Thanks for suggesting this workaround @samuelduchesne. Added a note to the README.

Background is that I don't have a paid Apple Developer membership that would allow me to codesign and notarize the app. Therefore, best is to remove the quarantine attribute after downloading with a web browser, or to use `wget` or `curl` to download it instead, which won't set the quarantine attribute.
